[package]
name = "nat"
version = "1.0.6"
authors = ["Will Lane <williamlane923@gmail.com>"]
edition = "2018"


[dependencies]
termion = "*"
chrono = "*"
users = "*"
pretty-bytes = "*"
ansi_term = "*"
structopt = "*"
