[package]
name = "nat"
version = "1.0.4"
authors = ["Will Lane <williamlane923@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
chrono = "*"
users = "*"
pretty-bytes = "*"
ansi_term = "*"
structopt = "*"
